# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('submit_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['score', 'submit_date', 'username'],
            },
        ),
    ]
